### ISSUE TITLE
"Error: did not find expected authorization request details in session" occurring with two tabs open

### ISSUE THREAD

**Issue by maxime-bc** [austincunningham/keycloak-express-openid-client#5]
Hello,

First of all, thank you for this repository as it is a valuable help to migrate from the deprecated Keycloak Node.js adapter.

I used your code in my project, and it works well with `Keycloak 20.0.2`. However, I had an issue and I was able to reproduce it in this repository.

It occurs with the following steps :
1. Click on "Test" and log in via the Keycloak login page, then open a second tab,
2. Logout form the second tab,
3. Refresh the first tab (either by pressing F5 or by clicking on "Test") : it redirects us to the Keycloak login page,
4. In the second tab, navigate to "Test" and log in again,
5. (a) Refresh the first tab => the error occurs,
(b) Instead of refreshing the page, log in. Keycloak notify you that you are already logged-in. If you press the browser back arrow button => the same error occurs,

```
Error: did not find expected authorization request details in session, req.session["oidc:127.0.0.1"] is undefined
    at /home/user/keycloak-express-openid-client/node_modules/openid-client/lib/passport_strategy.js:121:13
    at OpenIDConnectStrategy.authenticate (/home/user/keycloak-express-openid-client/node_modules/openid-client/lib/passport_strategy.js:180:5)b
    at attempt (/home/user/keycloak-express-openid-client/node_modules/passport/lib/middleware/authenticate.js:369:16)
    at authenticate (/home/user/keycloak-express-openid-client/node_modules/passport/lib/middleware/authenticate.js:370:7)
    at file:///home/user/keycloak-express-openid-client/index.js:70:7
    at Layer.handle [as handle_request] (/home/user/keycloak-express-openid-client/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/user/keycloak-express-openid-client/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/user/keycloak-express-openid-client/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/user/keycloak-express-openid-client/node_modules/express/lib/router/layer.js:95:5)
    at /home/user/keycloak-express-openid-client/node_modules/express/lib/router/index.js:284:15
```

I am new to Keycloak and I don't really know where to start to try to solve this. I searched a solution on the net to no avail.

I am using Keycloak `20.0.2`, and it also happens with Keycloak `17.0.0`. I am using the exact code of this repository, without any modifications.

Thanks you in advance for your help.

**Comment by maxime-bc** [comment]
**Update:** I migrated from `openid-client` and `passport` to `express-openid-connect` as I encountered other non-related issues.

But even with `express-openid-connect`, logging in in two different tabs would raise an error: `checks.state argument is missing`. I think that the two errors are related as `express-openid-connect` uses internally `openid-client`.

The best way to handle the `checks.state argument is missing` error for `express-openid-connect` is explained in [this issue](https://github.com/auth0/express-openid-connect/issues/467#issuecomment-1525985696).
I think that the same can be done with `openid-client` to mitigate the `did not find expected authorization request details in session`.
